version: '3.8'
services:
  todolist:
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres_db:5432/postgres'
    links:
      - postgres_db
    depends_on:
      - postgres_db
    ports:
      - '8080:8080'

  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  migration:
    image: arigaio/atlas:latest
    command: >
      migrate apply
      --url postgresql://postgres:postgres123@postgres_db:5432/postgres?sslmode=disable
    volumes:
      - ./db/migrations:/migrations
    depends_on:
      - postgres_db
    links:
      - postgres_db
