version: '3.8'
services:
  todolist:
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres_db:5432/postgres'
    links:
      - postgres_db
    depends_on:
      - init-db
    ports:
      - '8080:8080'

  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  init-db:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres_db:5432/postgres -schemas=public -user=postgres -password=postgres123 -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres_db
    links:
      - postgres_db

  migrate:
    image: arigaio/atlas:latest
    command: >
      migrate apply 
      --url 'postgresql://postgres:postgres123@postgres_db:5432/postgres?sslmode=disable'
    depends_on:
      - postgres_db
    links:
      - postgres_db
    volumes:
      - ./db/new/migrations/:/migrations

  migrate-seed:
    image: arigaio/atlas:latest
    command: >
      migrate apply 
      --url 'postgresql://postgres:postgres123@postgres_db:5432/postgres?sslmode=disable'
      --allow-dirty
    depends_on:
      - postgres_db
    links:
      - postgres_db
    volumes:
      - ./db/new/migrations/:/migrations