server:
  port: 8080

debug: true

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

