apiVersion: apps/v1
kind: Deployment
metadata:
  name: flyway-demo
  labels:
    app.kubernetes.io/name: flyway-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: flyway-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flyway-demo
    spec:
      imagePullSecrets:
        - name: dockerconfigjson
      containers:
        - name: flyway-demo
          image: ghcr.io/schumann-it/flyway-demo:sha-c438bc8
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgresql:5432/public"
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: spring-datasource-password
                  optional: false
          ports:
            - containerPort: 8080