apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  - pull-secret.yaml
  - postgresql-secret.yaml
  - deployment.yaml
  - service.yaml

helmCharts:
  - name: db-migrate
    valuesFile: db-migrate-values.yaml
  - name: postgresql
    repo: https://cetic.github.io/helm-charts
    valuesFile: postgresql-values.yaml