fullnameOverride: postgresql

postgresql:
  username: postgres
  password: postgres123
  database: public
  port: 5432
  # initdbArgs
  # initdbWalDir
  dataDir: /var/lib/postgresql/data/pgdata

##
## Init containers parameters:
## volumePermissions: Change the owner of the persist volume mountpoint to RunAsUser:fsGroup
##
volumePermissions:
  enabled: false

## Pod Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
##
securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: false
  mountPath: /var/lib/postgresql
  subPath: ""
  accessModes:  [ReadWriteOnce]
  ## Storage Capacity for persistent volume
  size: 10Gi
  annotations: {}
