kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: dockerconfigjson
  labels:
    app.kubernetes.io/name: flyway-demo
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJkWE5sY201aGJXVTZaMmh3WDJ4eVdFSkZSemRMTUVkYU1HcEVTRGc0YkRKTFZESjNTRXRRWkRGWE1qSTNkWGxuUlE9PSJ9fX0=